[project]
name = "ai-prompt-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anytree>=2.13.0",
    "requests>=2.32.3",
]
